In [16]:
import numpy as np
import pandas as pd

In [17]:
df = pd.read_excel("../Week02/ifood.xlsx")

In [18]:
df.head(5)

,No,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Age,Customer_Days,Marital,Education
0,1,58138,0,0,58,635,88,546,172,88,...,0,0,0,0,0,1,63,2822,Single,Graduation
1,2,46344,1,1,38,11,1,6,2,1,...,0,0,0,0,0,0,66,2272,Single,Graduation
2,3,71613,0,0,26,426,49,127,111,21,...,0,0,0,0,0,0,55,2471,Together,Graduation
3,4,26646,1,0,26,11,4,20,10,3,...,0,0,0,0,0,0,36,2298,Together,Graduation
4,5,58293,1,0,94,173,43,118,46,27,...,0,0,0,0,0,0,39,2320,Married,PhD

In [19]:
df.tail(5)

,No,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Age,Customer_Days,Marital,Education
2200,2201,61223,0,1,46,709,43,182,42,118,...,0,0,0,0,0,0,53,2540,Married,Graduation
2201,2202,64014,2,1,56,406,0,30,0,0,...,0,0,1,0,0,0,74,2178,Together,PhD
2202,2203,56981,0,0,91,908,48,217,32,12,...,1,0,0,0,0,0,39,2314,Divorced,Graduation
2203,2204,69245,0,1,8,428,30,214,80,30,...,0,0,0,0,0,0,64,2315,Together,Master
2204,2205,52869,1,1,40,84,3,61,2,1,...,0,0,0,0,0,1,66,2781,Married,PhD

In [20]:
df.describe()

,No,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Age,Customer_Days
count,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,...,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.00000,2205.000000,2205.000000
mean,1103.000000,51622.094785,0.442177,0.506576,49.009070,306.164626,26.403175,165.312018,37.756463,27.128345,...,5.336961,0.073923,0.074376,0.073016,0.064399,0.013605,0.009070,0.15102,51.095692,2512.718367
std,636.672993,20713.063826,0.537132,0.544380,28.932111,337.493839,39.784484,217.784507,54.824635,41.130468,...,2.413535,0.261705,0.262442,0.260222,0.245518,0.115872,0.094827,0.35815,11.705801,202.563647
min,1.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,24.000000,2159.000000
25%,552.000000,35196.000000,0.000000,0.000000,24.000000,24.000000,2.000000,16.000000,3.000000,1.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,43.000000,2339.000000
50%,1103.000000,51287.000000,0.000000,0.000000,49.000000,178.000000,8.000000,68.000000,12.000000,8.000000,...,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,50.000000,2515.000000
75%,1654.000000,68281.000000,1.000000,1.000000,74.000000,507.000000,33.000000,232.000000,50.000000,34.000000,...,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,61.000000,2688.000000
max,2205.000000,113734.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,262.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,80.000000,2858.000000

In [25]:
df['Income']
df2 = df['Income']                  #ข้อมูลยังมีการเชื่อมโยงกันอยู่ ถ้าเปลี่ยนค่าใน df2 จะเปลี่ยนค่าใน df ด้วย
df3 = df['Income'].copy(deep=True)  #ข้อมูลจะไม่เชื่อมโยงกัน ถ้าเปลี่ยนค่าใน df2 จะไม่เปลี่ยนค่าใน df

In [22]:
new_df = [["Age", "Income", "Gender"]]

In [23]:
#df.loc[100:105, ["Age", "Income", "Gender"]]
df.iloc[0:5, 0:3]

   No  Income  Kidhome
0   1   58138        0
1   2   46344        1
2   3   71613        0
3   4   26646        1
4   5   58293        1

In [ ]:
df[df['Age'] > 30][["No", "Age", "Income", "Gender"]]

KeyError: "['Gender'] not in index"